/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetointerfacegrafica;

import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import modelDominio.ContaBancaria;
        /**
         *
         * @author Guilherme
         */





import java.util.LinkedList;
import modelDominio.Cliente;
import modelDominio.ContaEspecial;
import modelDominio.ContaPoupanca;

public class TelaCadrastroConta extends javax.swing.JFrame {
    LinkedList<Cliente> listaClientes;
    LinkedList<ContaBancaria> listaContaBancaria;

    /**
     * Creates new form TelaCadrastroConta
     */
    public TelaCadrastroConta(LinkedList<Cliente> listaCliente, LinkedList<ContaBancaria>listaContaBancarias) {
        initComponents();
        this.listaClientes = listaCliente;
        this.listaContaBancaria = listaContaBancarias;
        
        jTFLimite.setEditable(false);
        jTFDia.setEditable(false);
        
        carregaComboBox();
    }
    public void carregaComboBox(){
        jCBCliente.addItem("<< Selecionar >>");
        for(int i = 0; i < this.listaClientes.size(); i++){
            Cliente meuCliente = this.listaClientes.get(i);
            jCBCliente.addItem(meuCliente.getCpf()+ " - "+meuCliente.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLSaldo = new javax.swing.JLabel();
        jTFSaldo = new javax.swing.JTextField();
        jBCancelar = new javax.swing.JButton();
        jBSalvar1 = new javax.swing.JButton();
        jLTipo = new javax.swing.JLabel();
        jCBTipoConta = new javax.swing.JComboBox<>();
        jLLimite = new javax.swing.JLabel();
        jTFDia = new javax.swing.JTextField();
        jLDia = new javax.swing.JLabel();
        jTFLimite = new javax.swing.JTextField();
        jLCliente = new javax.swing.JLabel();
        jCBCliente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de cadrasto");

        jLSaldo.setText("Saldo: ");

        jBCancelar.setText("Calcelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBSalvar1.setText("Salvar");
        jBSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvar1ActionPerformed(evt);
            }
        });

        jLTipo.setText("Tipo: ");

        jCBTipoConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<< Selecionar >>", "Bancaria", "Especial", "Poupança" }));
        jCBTipoConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipoContaActionPerformed(evt);
            }
        });

        jLLimite.setText("Limite: ");

        jLDia.setText("Dia: ");

        jLCliente.setText("Cliente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLDia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTFDia, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLLimite)
                        .addGap(18, 18, 18)
                        .addComponent(jTFLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jCBCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jCBTipoConta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTFSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jBSalvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCliente)
                    .addComponent(jCBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSaldo)
                    .addComponent(jTFSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTipo)
                    .addComponent(jCBTipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLLimite)
                    .addComponent(jTFLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDia)
                    .addComponent(jTFDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancelar)
                    .addComponent(jBSalvar1))
                .addGap(145, 145, 145))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvar1ActionPerformed
        // TODO add your handling code here:
        
            if (jCBCliente.getSelectedIndex() != 0) {
                if (!jTFSaldo.getText().equals("")) {
                    if (jCBTipoConta.getSelectedIndex() != 0) {
                        int posicao = jCBCliente.getSelectedIndex();
                        Cliente meuCliente = this.listaClientes.get(posicao - 1);
                        float saldo = Float.parseFloat(jTFSaldo.getText());

                        //verificando o tipo de conta
                        if (jCBTipoConta.getSelectedIndex() == 1) { //bancaria
                            // criando a conta
                            ContaBancaria minhaConta = new ContaBancaria(meuCliente, saldo);

                            listaContaBancaria.add(minhaConta);

                            JOptionPane.showMessageDialog(rootPane, "Conta cadrastada com sucesso!");
                            limpaCampus();

                        } else if (jCBTipoConta.getSelectedIndex() == 2) { // especial
                            // verificando se informou o limite
                            if (!jTFLimite.getText().equals("")) {
                                // obtendo o limite
                                float limite = Float.parseFloat(jTFLimite.getText());
                                ContaEspecial minhaContaEspecial = new ContaEspecial(limite, meuCliente, saldo);
                                listaContaBancaria.add(minhaContaEspecial);
                                JOptionPane.showMessageDialog(rootPane, "Conta cadrastada com sucesso!");
                                limpaCampus();
                                
                            } else {
                                JOptionPane.showMessageDialog(rootPane, "Erro: Informe o limite");
                            }

                        } else if (jCBTipoConta.getSelectedIndex() == 3) { // poupanca
                            if(jTFDia.getText().equals("")){
                                int dia = Integer.parseInt(jTFDia.getText());
                                ContaPoupanca minhaContaPoupanca = new ContaPoupanca(dia, meuCliente, saldo);
                                listaContaBancaria.add(minhaContaPoupanca);
                                JOptionPane.showMessageDialog(rootPane, "Conta cadrastada com sucesso!");
                                limpaCampus();
                                
                            }else{
                                JOptionPane.showMessageDialog(rootPane, "Erro: Informe o dia de rendimento");
                            }
                        }

                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Erro: Informe o tipo de conta");

                    }

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Erro: informe o saldo");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro: informe o cliente");
        }
    }//GEN-LAST:event_jBSalvar1ActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        limpaCampus();

    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jCBTipoContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoContaActionPerformed
        // TODO add your handling code here:
        //verificando a seleçao na combo
        if (jCBTipoConta.getSelectedIndex() == 0 || jCBTipoConta.getSelectedIndex() == 1) {
            jTFLimite.setEditable(false);
            jTFDia.setEditable(false);
        } else if (jCBTipoConta.getSelectedIndex() == 2) {
            jTFLimite.setEditable(true);
            jTFDia.setEditable(false);
        } else if (jCBTipoConta.getSelectedIndex() == 3) {
            jTFLimite.setEditable(false);
            jTFDia.setEditable(true);
        }
    }//GEN-LAST:event_jCBTipoContaActionPerformed

    public void limpaCampus() {
        jCBCliente.setSelectedIndex(0);
        jTFSaldo.setText("");
        jCBTipoConta.setSelectedIndex(0);
        jTFLimite.setText("");
        jTFDia.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBSalvar1;
    private javax.swing.JComboBox<String> jCBCliente;
    private javax.swing.JComboBox<String> jCBTipoConta;
    private javax.swing.JLabel jLCliente;
    private javax.swing.JLabel jLDia;
    private javax.swing.JLabel jLLimite;
    private javax.swing.JLabel jLSaldo;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JTextField jTFDia;
    private javax.swing.JTextField jTFLimite;
    private javax.swing.JTextField jTFSaldo;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
