/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetointerfacegrafica;

import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelDominio.ContaBancaria;
import modelDominio.ContaEspecial;
import modelDominio.ContaPoupanca;

/**
 *
 * @author Guilherme
 */
public class TelaVisualizacaoContas2 extends javax.swing.JFrame {
    //declarando a lista
     LinkedList<ContaBancaria> listaContaBancaria;
    /**
     * Creates new form TelaVisualizaçaoContas
     */
    public TelaVisualizacaoContas2(LinkedList<ContaBancaria> listaContaBancaria) {
        initComponents();
        //atribuindo a lista
        this.listaContaBancaria = listaContaBancaria;
        atualizaTabela();
    }
    //metodo responsavel por carregar a tabela
    public void atualizaTabela(){
        DefaultTableModel modelo = (DefaultTableModel)jTContas.getModel();
        modelo.setNumRows(0);
        
        for(int i = 0; i < this.listaContaBancaria.size(); i++){
            ContaBancaria minhaConta = this.listaContaBancaria.get(i);
            modelo.addRow(new Object[] {""});
            modelo.setValueAt(minhaConta.getNomeTitular(), i, 0);
            modelo.setValueAt(minhaConta.getCpfTitular(), i, 1);
            modelo.setValueAt(minhaConta.getSaldo(), i, 2);
            
            String tipo = "";
            if(minhaConta instanceof ContaEspecial){
                tipo = "Especial";
                //modelo.setValueAt("Especial", i, 3);
            }else if(minhaConta instanceof ContaPoupanca){
                tipo = "Poupanca";
                //modelo.setValueAt("Poupanca", i, 3);
            }else{
                tipo = "Bancaria";
            }
            modelo.setValueAt(tipo, i, 3);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTContas = new javax.swing.JTable();
        jBDetalhar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de visualizacao de contas");

        jTContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Saldo", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTContas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTContasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTContas);

        jBDetalhar.setText("Detalhar");
        jBDetalhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDetalharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBDetalhar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jBDetalhar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBDetalharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDetalharActionPerformed
        // TODO add your handling code here:
        //verificando se o ususario selecionou uma conta
        if(jTContas.getSelectedRow() != -1){
            //obtendo a conta selecionada
           mostraContaBancaria();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Erro: selecio a conta desejada");
        }
    }//GEN-LAST:event_jBDetalharActionPerformed

    private void jTContasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTContasMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            mostraContaBancaria();
        }
    }//GEN-LAST:event_jTContasMouseClicked

    public void mostraContaBancaria(){
         ContaBancaria minhaConta =this.listaContaBancaria.get(jTContas.getSelectedRow());
            JOptionPane.showMessageDialog(rootPane, "Nome: "+minhaConta.getNomeTitular()+ ", CPF: "+minhaConta.getCpfTitular()+ ", Saldo: "+minhaConta.getSaldo());
           
            //verificando se tratace de uma das sub classes 
            if(minhaConta instanceof ContaEspecial){
                ContaEspecial minhaContaEspecial = (ContaEspecial) minhaConta;
                JOptionPane.showMessageDialog(rootPane, "Limite: "+minhaContaEspecial.getLimite());
            }else if(minhaConta instanceof ContaPoupanca){
                ContaPoupanca minhaContaPoupanca = (ContaPoupanca) minhaConta;
                JOptionPane.showMessageDialog(rootPane, "Dia de Rendimento: "+minhaContaPoupanca.getDiaRendimento());
            }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDetalhar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTContas;
    // End of variables declaration//GEN-END:variables
}

