/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhofinal;
import TrabalhoModelDominio.Produto;
import TrabalhoModelDominio.Vendas;

import java.awt.Container;
import java.util.LinkedList;
import javax.swing.JOptionPane;
/**
 *
 * @author vitie
 */
public class cadastrodevendas extends javax.swing.JFrame {

         LinkedList<Produto> listaProdutos;
         LinkedList<Vendas > listaVendas;
    /**
     * Creates new form CadastrodeVenda
     */
    public cadastrodevendas(LinkedList<Produto> listaProdutos, LinkedList<Vendas > listaVendas) {
        initComponents();
         //inicializando a lista 
        this.listaProdutos = listaProdutos;
        this.listaVendas = listaVendas;
        CarregaCombo();
    }

    cadastrodevendas() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
        public void  CarregaCombo(){
           
            for(int i =0; i<this.listaProdutos.size(); i++){
                //obtendo as coisas
                Produto meuProduto = this.listaProdutos.get(i);
                jCBProduto.addItem(meuProduto.getNome());
                
            }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLDataVenda = new javax.swing.JLabel();
        jTFDataVenda = new javax.swing.JTextField();
        jLProduto = new javax.swing.JLabel();
        jBSalvar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jCBProduto = new javax.swing.JComboBox<>();
        jLQuantidade = new javax.swing.JLabel();
        jTFQuantidade = new javax.swing.JTextField();
        jLNomeCliente = new javax.swing.JLabel();
        jTFNomeCliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLDataVenda.setText("Data Venda:");

        jLProduto.setText("Produto:");

        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jCBProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<<Selecionar>>" }));
        jCBProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBProdutoActionPerformed(evt);
            }
        });

        jLQuantidade.setText("Quantidade:");

        jLNomeCliente.setText("Nome cliente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLDataVenda)
                            .addComponent(jLProduto)
                            .addComponent(jLQuantidade))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLNomeCliente)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFNomeCliente)
                    .addComponent(jTFDataVenda)
                    .addComponent(jCBProduto, 0, 243, Short.MAX_VALUE)
                    .addComponent(jTFQuantidade))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNomeCliente)
                    .addComponent(jTFNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDataVenda)
                    .addComponent(jTFDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLProduto)
                    .addComponent(jCBProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLQuantidade)
                    .addComponent(jTFQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalvar)
                    .addComponent(jBCancelar))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        // TODO add your handling code here:
        if(!jTFNomeCliente.getText().equals("")){
            if(!jTFDataVenda.getText().equals("")){
                if(!jTFQuantidade.getText().equals("")){
                    if(jCBProduto.getSelectedIndex()!=0){
                        String nomeCliente = (jTFNomeCliente.getText());
                        String dataVenda=(jTFDataVenda.getText());
                        int quantidade =Integer.parseInt (jTFQuantidade.getText());
                        int posicao= jCBProduto.getSelectedIndex();
                        Produto produto = this.listaProdutos.get(posicao-1);

                        if(quantidade < produto.getQuantidade()){

                            Vendas minhasVendas = new Vendas (nomeCliente, dataVenda, quantidade, produto);
                            this.listaVendas.add(minhasVendas);

                            JOptionPane.showMessageDialog(rootPane, "Parabéns: Sua venda foi efetuada!!!");
                            LimpaCampos();

                        }else{
                            JOptionPane.showMessageDialog(rootPane, "Erro: a quantidade que deseja não disponível!!!");

                        }

                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Erro: informe a quantidade desejada!!!");

                    }
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Erro: informe o produto desejado!!!");

                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Erro: informe a data da venda!!!");

            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Erro: informe o seu nome!!!");

        }

    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        LimpaCampos();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jCBProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBProdutoActionPerformed
     
    
        public void LimpaCampos(){
        jTFNomeCliente.setText("");
        jTFDataVenda.setText("");
        jTFQuantidade.setText("");
        jCBProduto.setSelectedIndex(0);
        
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JComboBox<String> jCBProduto;
    private javax.swing.JLabel jLDataVenda;
    private javax.swing.JLabel jLNomeCliente;
    private javax.swing.JLabel jLProduto;
    private javax.swing.JLabel jLQuantidade;
    private javax.swing.JTextField jTFDataVenda;
    private javax.swing.JTextField jTFNomeCliente;
    private javax.swing.JTextField jTFQuantidade;
    // End of variables declaration//GEN-END:variables
}
