/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhofinal;

import TrabalhoModelDominio.Bebida;
import TrabalhoModelDominio.Comestivel;
import TrabalhoModelDominio.Produto;
import TrabalhoModelDominio.Vendas;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vitie
 */
public class VisualizacaoDeVendas extends javax.swing.JFrame {
        LinkedList<Vendas>listaVendas;
        LinkedList<Produto>listaProdutos;
    /**
     * Creates new form VisualizacaoDeVendas
     */
    public VisualizacaoDeVendas(LinkedList<Vendas> listaVendas, LinkedList<Produto> listaProdutos) {
        initComponents();
        this.listaVendas= listaVendas;
        this.listaProdutos = listaProdutos;
        atualizaTabela();
        
    }

    private VisualizacaoDeVendas() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
    public void atualizaTabela(){
        DefaultTableModel vendas =(DefaultTableModel)jTVisualizacaoDeVendas.getModel();
        vendas.setNumRows(0);
        
        for(int x =0; x<this.listaVendas.size();x++){
            Vendas minhasVendas = this.listaVendas.get(x);
            vendas.addRow(new Object[]{""});
            
            vendas.setValueAt(minhasVendas.getNomeCliente(), x, 0);
            vendas.setValueAt(minhasVendas.getDataVenda(), x, 1);
            vendas.setValueAt(minhasVendas.getProduto().getNome(), x, 2);
            vendas.setValueAt(minhasVendas.getValorVenda(), x, 3);
            
        }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBDetalhar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTVisualizacaoDeVendas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBDetalhar.setText("Detalhar:");
        jBDetalhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDetalharActionPerformed(evt);
            }
        });

        jTVisualizacaoDeVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cliente", "Data", "Produto", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTVisualizacaoDeVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTVisualizacaoDeVendas(evt);
            }
        });
        jScrollPane1.setViewportView(jTVisualizacaoDeVendas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBDetalhar)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jBDetalhar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBDetalharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDetalharActionPerformed
        // TODO add your handling code here:
         //verificando se o ususario selecionou algum elemento da lista
        if(jTVisualizacaoDeVendas.getSelectedRow()!= -1){
            //obtendo as coisas
            int posicao = jTVisualizacaoDeVendas.getSelectedRow();
            Vendas minhasVendas = this.listaVendas.get(posicao);
            //mostrando as informações 
            JOptionPane.showMessageDialog(rootPane, "Nome:"+ minhasVendas.getNomeCliente()
                +"Data:"+ minhasVendas.getDataVenda()
                +"Produto:"+ minhasVendas.getProduto().getNome()
                +"Valor Venda: "+ minhasVendas.getValorVenda()
                +"Quantidade:"+ minhasVendas.getQuantidade());
           
    }else{
        JOptionPane.showMessageDialog(rootPane, "Erro: selecione a conta que deseja!!!");
    }
        
    }//GEN-LAST:event_jBDetalharActionPerformed

    private void jTVisualizacaoDeVendas(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTVisualizacaoDeVendas
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
          
        }
    }//GEN-LAST:event_jTVisualizacaoDeVendas

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDetalhar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTVisualizacaoDeVendas;
    // End of variables declaration//GEN-END:variables
}
