/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TrabalhoFinal;

import ModelDominio.Produto;
import ModelDominio.Venda;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilherme
 */
public class TelaCadastroVenda extends javax.swing.JFrame {

    LinkedList<Produto> listaProduto;
    LinkedList<Venda> listaVenda;

    /**
     * Creates new form TelaCadastroVenda
     */
    public TelaCadastroVenda(LinkedList<Produto> listaProduto, LinkedList<Venda> listaVenda) {
        initComponents();
        this.listaProduto = listaProduto;
        this.listaVenda = listaVenda;
        CarregaCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLDataVenda = new javax.swing.JLabel();
        jTFDataVenda = new javax.swing.JTextField();
        jLProduto = new javax.swing.JLabel();
        jCBProduto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTFQuantidade = new javax.swing.JTextField();
        jBSalvar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLNomeCliente = new javax.swing.JLabel();
        jTFNomeCliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Vendas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 0, 153))); // NOI18N

        jLDataVenda.setText("Data Venda");

        jLProduto.setText("Produto");

        jCBProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<<Selecionar>>" }));
        jCBProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBProdutoActionPerformed(evt);
            }
        });

        jLabel1.setText("Quantidade");

        jBSalvar.setBackground(new java.awt.Color(102, 0, 153));
        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        jBCancelar.setBackground(new java.awt.Color(102, 0, 153));
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jLNomeCliente.setText("Nome Cliente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNomeCliente)
                            .addComponent(jLDataVenda)
                            .addComponent(jLProduto)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFNomeCliente)
                            .addComponent(jTFDataVenda)
                            .addComponent(jCBProduto, 0, 200, Short.MAX_VALUE)
                            .addComponent(jTFQuantidade))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNomeCliente)
                    .addComponent(jTFNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDataVenda)
                    .addComponent(jTFDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLProduto)
                    .addComponent(jCBProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBProdutoActionPerformed

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        // TODO add your handling code here:
        if (!jTFNomeCliente.getText().equals("")) {
            if (!jTFDataVenda.getText().equals("")) {
                if (!jTFQuantidade.getText().equals("")) {
                    if (jCBProduto.getSelectedIndex() != 0) {
                        String nomeCliente = (jTFNomeCliente.getText());
                        String dataVenda = (jTFDataVenda.getText());
                        int quantidade = Integer.parseInt(jTFQuantidade.getText());
                        int posicao = jCBProduto.getSelectedIndex();
                        Produto produto = this.listaProduto.get(posicao - 1);

                        if (quantidade <= produto.getQuantidade()) {

                            Venda minhasVendas = new Venda(nomeCliente, dataVenda, quantidade, produto);
                            this.listaVenda.add(minhasVendas);

                            JOptionPane.showMessageDialog(rootPane, " Sua venda foi efetuada");
                            LimpaCampos();

                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Erro: a quantidade não disponível");

                        }

                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Erro: informe a quantidade");

                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Erro: informe o produto");

                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro: informe a data da venda");

            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Erro: informe o seu nome");

        }

    }//GEN-LAST:event_jBSalvarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        LimpaCampos();
    }//GEN-LAST:event_jBCancelarActionPerformed

    
     public void LimpaCampos(){
        jTFNomeCliente.setText("");
        jTFDataVenda.setText("");
        jTFQuantidade.setText("");
        jCBProduto.setSelectedIndex(0);
    }
     
     public void  CarregaCombo(){
           
            for(int i =0; i<this.listaProduto.size(); i++){
                //obtendo as coisas
                Produto meuProduto = this.listaProduto.get(i);
                jCBProduto.addItem(meuProduto.getNome());
                
            }
        }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JComboBox<String> jCBProduto;
    private javax.swing.JLabel jLDataVenda;
    private javax.swing.JLabel jLNomeCliente;
    private javax.swing.JLabel jLProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFDataVenda;
    private javax.swing.JTextField jTFNomeCliente;
    private javax.swing.JTextField jTFQuantidade;
    // End of variables declaration//GEN-END:variables
}
