/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cantina;

import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelDominio.Produto;
import modelDominio.Venda;

/**
 *
 * @author Guilherme
 */
public class TelaVisualizacaoVenda extends javax.swing.JFrame {

    LinkedList<Produto> listaProduto;
    LinkedList<Venda> listaVenda;

    /**
     * Creates new form TelaVisualizacaoVenda
     */
    public TelaVisualizacaoVenda(LinkedList<Produto> listaProduto, LinkedList<Venda> listaVenda) {
        initComponents();
        this.listaProduto = listaProduto;
        this.listaVenda = listaVenda;

    }

    public void atualizaTabela() {
        DefaultTableModel venda = (DefaultTableModel) jTVisualizacaoDeVendas.getModel();
        venda.setNumRows(0);

        for (int x = 0; x < this.listaVenda.size(); x++) {
            Venda minhasVendas = this.listaVenda.get(x);
            venda.addRow(new Object[]{""});

            venda.setValueAt(minhasVendas.getNomeCliente(), x, 0);
            venda.setValueAt(minhasVendas.getDataVenda(), x, 1);
            venda.setValueAt(minhasVendas.getProduto().getNome(), x, 2);
            venda.setValueAt(minhasVendas.getValorVenda(), x, 3);

        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTVisualizacaoDeVendas = new javax.swing.JTable();
        jBDetalhar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTVisualizacaoDeVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cliente", "Data", "Produto", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTVisualizacaoDeVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTVisualizacaoDeVendas(evt);
            }
        });
        jScrollPane1.setViewportView(jTVisualizacaoDeVendas);

        jBDetalhar.setText("Detalahar");
        jBDetalhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDetalharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBDetalhar)
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jBDetalhar)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTVisualizacaoDeVendas(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTVisualizacaoDeVendas
        // TODO add your handling code here:
    }//GEN-LAST:event_jTVisualizacaoDeVendas

    private void jBDetalharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDetalharActionPerformed
        // TODO add your handling code here:
        if (jTVisualizacaoDeVendas.getSelectedRow() != -1) {
            //obtendo as coisas
            int posicao = jTVisualizacaoDeVendas.getSelectedRow();
            Venda minhasVendas = this.listaVenda.get(posicao);
            //mostrando as informações 
            JOptionPane.showMessageDialog(rootPane, "Nome:" + minhasVendas.getNomeCliente()
                    + "Data:" + minhasVendas.getDataVenda()
                    + "Produto:" + minhasVendas.getProduto().getNome()
                    + "Valor Venda: " + minhasVendas.getValorVenda()
                    + "Quantidade:" + minhasVendas.getQuantidade());

        } else {
            JOptionPane.showMessageDialog(rootPane, "Erro: selecione a conta que deseja!!!");
        }
    }//GEN-LAST:event_jBDetalharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDetalhar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTVisualizacaoDeVendas;
    // End of variables declaration//GEN-END:variables
}
